name: "Build a binary distribution"
inputs:
  cibw-only:
    required: true
  upload-name:
    required: true
runs:
  using: "composite"
  steps:
    - name: Python 3.14
      uses: actions/setup-python@v5
      with:
        python-version: 3.14

    - name: Print build identifiers
      shell: bash -l {0}
      run: |
        python -m pip install cibuildwheel
        python -m cibuildwheel --only ${{ inputs.cibw-only }} --print-build-identifiers

    - name: Install openmp
      uses: mamba-org/setup-micromamba@v2
      if: runner.os == 'macOS'
      with:
        micromamba-version: "latest"
        environment-name: omp
        create-args: >-
          llvm-openmp
        cache-environment: true

    - name: Set OPENMP_PREFIX (macOS)
      if: runner.os == 'macOS'
      shell: bash -l {0}
      run: |
        echo "OPENMP_PREFIX=${CONDA_PREFIX}" >> "$GITHUB_ENV"

    - name: Build wheels
      uses: pypa/cibuildwheel@v3.2.1
      with:
        only: ${{ inputs.cibw-only }}

    - uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.upload-name }}
        path: ${{ github.workspace }}/wheelhouse/*.whl
        overwrite: true
