# Reference:
#   - https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/keeping-your-actions-up-to-date-with-dependabot

version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "dependencies"
    labels: ["skip news", "dependencies"]

  - package-ecosystem: "pip"
    directory: "/requirements"
    schedule:
      interval: "daily"
    target-branch: "dependencies"
    labels: ["skip news", "dependencies"]
