version: 2

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false

formats:
  - htmlzip

python:
  version: 3.8
  install:
    - requirements: requirements-docs.txt
    - requirements: requirements.txt
    - method: pip
      path: .
  system_packages: false

build:
  image: latest
