version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false

python:
  install:
    - requirements: requirements/docs.txt
    - method: pip
      path: .
