environment:

  global:
    PYPI_PASS:
      secure: 8om/mA+rp/SBcVXDrFC9LgyKPcEmlseSUT4WBBOgfYM=
    ANACONDA_TOKEN:
      secure: +l38MCyFk16Wb40xBFaa8U/F5pvBAnIUlsYMXPjLCnnPbsPbpkSWwbk6084u/GCV
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\.ci\\appveyor\\run_with_env.cmd"

  matrix:

    - TARGET_ARCH: x64
      CONDA_NPY: 111
      CONDA_INSTALL_LOCN: C:\\Miniconda37-x64
      CONDA_PY: 3.7

    - TARGET_ARCH: x64
      CONDA_NPY: 111
      CONDA_INSTALL_LOCN: C:\\Miniconda36-x64
      CONDA_PY: 3.6

platform:
  - x64

os: Previous Visual Studio 2015
# os: Visual Studio 2013

init:
  - "ECHO %CONDA_INSTALL_LOCN% %CONDA_PY% %HOME% %PLATFORM%"
  - "ECHO %APPVEYOR_REPO_BRANCH%"

install:
  - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
  - cmd: conda update --yes --quiet conda
  - cmd: set PYTHONUNBUFFERED=1
  - cmd: conda config --set always_yes yes
  - cmd: pip install twine -r requirements-testing.txt -r requirements-notebooks.txt
  - cmd: conda info
  - cmd: conda list

build: false

test_script:
  - "%WITH_COMPILER% pip install numpy"
  - "%WITH_COMPILER% pip install netcdf4==1.5.2"
  - "%WITH_COMPILER% pip install -e ."
  - pytest -vvv

after_test:
  - cmd: python setup.py bdist_wheel

artifacts:
  # Archive the generated conda package in the ci.appveyor.com build report.
  - path: 'dist\*'

deploy_script:
  - cmd: python .ci/appveyor/pypi_upload.py

notifications:
  - provider: Slack
    auth_token:
      secure: hvij8zEmE9LqjvwUJteiIZdwutlETmcJWwI/PtQEiAn3Hb2J+SH0Ye+pxMot2J2mc4i+zeNpHlzu8NV2CcLXzA==
    channel: "#testing"
