environment:

  global:
    PYPI_PASS:
      secure: 8om/mA+rp/SBcVXDrFC9LgyKPcEmlseSUT4WBBOgfYM=
    ANACONDA_TOKEN:
      secure: +l38MCyFk16Wb40xBFaa8U/F5pvBAnIUlsYMXPjLCnnPbsPbpkSWwbk6084u/GCV
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\.ci\\appveyor\\run_with_env.cmd"

  matrix:

    - TARGET_ARCH: x64
      PYTHON: "C:\\Python38-x64"

    - TARGET_ARCH: x64
      PYTHON: "C:\\Python37-x64"

    - TARGET_ARCH: x64
      PYTHON: "C:\\Python36-x64"

platform:
  - x64

# os: Previous Visual Studio 2015
# os: Visual Studio 2013

init:
  - "ECHO %PYTHON% %HOME% %PLATFORM%"
  - "ECHO %APPVEYOR_REPO_BRANCH%"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "%WITH_COMPILER% pip install twine wheel -r requirements-testing.txt -r requirements-notebooks.txt"
  - "%WITH_COMPILER% python -VV"

build: false

test_script:
  - "%WITH_COMPILER% pip install numpy"
  - "%WITH_COMPILER% pip install netcdf4==1.5.2"
  - "%WITH_COMPILER% pip install -e ."
  - "%WITH_COMPILER% pytest -vvv"

after_test:
  - "%WITH_COMPILER% python setup.py bdist_wheel"

artifacts:
  # Archive the generated conda package in the ci.appveyor.com build report.
  - path: 'dist\*'

deploy_script:
  - cmd: "%WITH_COMPILER% python .ci/appveyor/pypi_upload.py"

notifications:
  - provider: Slack
    auth_token:
      secure: hvij8zEmE9LqjvwUJteiIZdwutlETmcJWwI/PtQEiAn3Hb2J+SH0Ye+pxMot2J2mc4i+zeNpHlzu8NV2CcLXzA==
    channel: "#testing"
