#!/usr/bin/env python
"""Base Species of SpeciesEvolver."""
from abc import ABC, abstractmethod


class _Species(ABC):
    """Base Species."""

    def __init__(self):
        self._identifier = ()
        self._parent_species = None

    @property
    def identifier(self):
        """The species identifier.

        Returns
        -------
        tuple
            The identifier of the species. The first element is the clade of a
            species represented by a string. The second element is the species
            number represented by an integer. The identifier is automatically
            generated by SpeciesEvolver.
        """
        return self._identifier

    @property
    def parent_species(self):
        """The parent species.

        Returns
        -------
        species
            The species object that produced the species. A value of `None`
            indicates no parent species.
        """
        return self._parent_species

    @property
    @abstractmethod
    def range_mask(self):
        """A mask of the species geographic extent.

        Abstract method.

        Returns
        -------
        boolean ndarray
            An array
        """
        ...  # pragma: no cover
