#!/usr/bin/env python
"""Base Species object of SpeciesEvolver .
"""
import numpy as np

from landlab.components.species_evolution import ZoneManager as zm


class Species(object):
    """The SpeciesEvolver base species.

    Species contains

    The identifier is a two element tuple automatically generated by
    SpeciesEvolver. The first element is the clade id designated by a letter or
    letters. The second element is the species number that is assigned
    sequentially for each clade. The clade id is passed to child species.
    """
    def __init__(self, initial_zones, parent_species=None):
        """Initialize a species.

        Parameters
        ----------
        initial_zones : SpeciesEvolver Zone or Zone list
            A list of SpeciesEvolver Zone objects of the species.
        parent_species : SpeciesEvolver Species
            The parent species object. The default value, 'None' indicates no
            parent species.
        """
        # Set parameters.
        self._identifier = None
        self.parent_species = parent_species

        # Set initial zone(s).
        if isinstance(initial_zones, list):
            z = initial_zones
        else:
            z = [initial_zones]
        self.zones = z

    def _evolve(self, time):
        """Run species evolutionary processes.

        Extinction is not explicitly implemented in this method. The base class
        of species leaves extinction to the disappearance of the range of a
        species.

        Parameters
        ----------
        time : float or int

        Returns
        -------
        output : dictionary
            Required keys:
                'species_persists' : boolean
                    `True` indicates that this species persists.
                    `False` indicates that this species is becomes extinct.
                'child_species' : SpeciesEvolver Species list
                    The child species produced by the current species after the
                    macroevolution processes run. An empty array indicates no
                    child species.
            Optional keys:
                'species_evolver_add_on' : dictionary
                    The items of this dictionary will become items in the
                    SpeciesEvolver records for this time.
        """
        species_persists = True
        child_species = []

        # Disperse and speciate. Extinction effectively occurs when the species
        # does not disperse to or remain in any zones.

        for z in self.zones:
            path_type = z.path[time][0]
            destinations = z.path[time][1]

            if path_type in [zm.ONE_TO_ONE, zm.MANY_TO_ONE]:
                # The species in this zone disperses to/remains in the zone.
                self.zones = destinations
                species_persists = True

            elif path_type in [zm.ONE_TO_MANY, zm.MANY_TO_MANY]:
                # The zone and the species within it was fragmented. A new
                # child species is added to every destination zone. The species
                # self does not continue. It is assumed to have evolved into
                # one of the child species.
                species_persists = False

                for d in destinations:
                    child_species_d = Species(d, parent_species=self)
                    child_species.append(child_species_d)

            elif path_type == zm.ONE_TO_NONE:
                species_persists = False

        # Create a unique array of child species.
        child_species = np.array(list(set(child_species)))

        return species_persists, child_species

    @property
    def identifier(self):
        """Get the species identifier.

        Returns
        -------
        identifier : tuple
            The unique identifier of the species. The first element is the
            clade of a species represented by a string. The second element is
            the species number represented by an integer.
        """
        return self._identifier

    @property
    def clade(self):
        """Get the species clade identifier.

        Returns
        -------
        clade_identifier : string
            The string representation of the clade of the species.
        """
        return self._identifier[0]
