{% set name = "landlab" %}
{% set data = load_setup_py_data() %}

package:
  name: {{ name }}
  version: {{ data.get('version') }}

source:
  path: ..

requirements:
  build:
    - {{ compiler("c") }}
  host:
    - python
    - pip
    - cython
    - numpy 1.11.*
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - xarray
    - matplotlib
    - netcdf4
    - six
    - pyyaml
    - statsmodels
    - pyshp

test:
  requires:
    - pytest
  imports:
    - landlab
  commands:
    - export MPLBACKEND=Agg  # [not win]
    - pytest --pyargs landlab --doctest-modules -o doctest_optionflags="NORMALIZE_WHITESPACE IGNORE_EXCEPTION_DETAIL ALLOW_UNICODE"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
