package:
  name: landlab
  version: "1.0.2"

source:
  path: ..

requirements:
  build:
    - python
    - libgcc # [linux and py27 and np == '19']
    - scipy
    - numpy x.x
    - xarray
    - nose
    - matplotlib
    - numpydoc
    - netcdf4
    - hdf4 >=4.2.12 # [not win and np == 111]
    - cython
    - six
    - pyyaml
    - setuptools

  run:
    - python
    - libgcc # [linux and py27 and np == '19']
    - scipy
    - numpy x.x
    - xarray
    - nose
    - matplotlib
    - numpydoc
    - netcdf4
    - hdf4 >=4.2.12 # [not win and np == 111]
    - cython
    - six
    - pyyaml
    - setuptools
    - xarray

build:
  string: {{ environ.get('BUILD_STR', '') }}
