package:
  name: landlab
  version: "1.2.0"

source:
  path: ..

requirements:
  build:
    - python
    - libgcc # [linux and py27 and np == '19']
    - scipy
    - numpy x.x
    - xarray
    - nose
    - matplotlib
    - numpydoc
    - netcdf4
    - cython
    - six
    - pyyaml
    - setuptools
    - statsmodels
    - jpeg <=8 # [osx and np==111]

  run:
    - python
    - libgcc # [linux and py27 and np == '19']
    - scipy
    - numpy x.x
    - xarray
    - nose
    - matplotlib
    - numpydoc
    - netcdf4
    - cython
    - six
    - pyyaml
    - setuptools
    - xarray
    - statsmodels
    - jpeg <=8 # [osx and np==111]

build:
  string: {{ environ.get('BUILD_STR', '') }}
