{% set name = "landlab" %}
{% set data = load_setup_py_data() %}

package:
  name: {{ name }}
  version: {{ data.get('version') }}

source:
  path: ..

requirements:
  build:
    - {{ compiler("c") }}
    - setuptools
    - python
    - cython
    - numpy 1.11.*

  run:
    - python
    - cython
    - numpy >=1.11,<1.14
    - scipy
    - xarray
    - matplotlib
    - numpydoc
    - netcdf4
    - six
    - pyyaml
    - statsmodels

test:
  requires:
    - pytest 3.7.4
  commands:
    - pytest --pyargs landlab --doctest-modules -o doctest_optionflags="NORMALIZE_WHITESPACE IGNORE_EXCEPTION_DETAIL ALLOW_UNICODE"

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
